### PR TITLE
changed osm to openstreetmap and changed protocal to https

### PR DESCRIPTION
**Pull request by alan-unravel**

### CODE REVIEW

**Comment by alan-unravel** [comment]
To fix #17

**Comment by alan-unravel** [comment]
Just for [reference](https://developer.mozilla.org/en/docs/Security/MixedContent) this shouldn't affect `http` users and is an issue for people who use it over `https`

**Comment by gordonwoodhull** [comment]
My concern was that it will make things a little slower for http users. Probably not a serious problem.

I've seen the problem with https. Guess I'll pull this now and parameterize later... Sometimes folks have their own tile servers.

**Comment by gordonwoodhull** [comment]
Thanks @alan-unravel!

**Comment by alan-unravel** [comment]
Thanks @gordonwoodhull

**Pull request merged**
