### PR TITLE
Fix maps not rendering properly due to improperly set div.dc-leaflet width and height

### LINKED ISSUE #5: Broken demo
The demo doesn't render the maps properly and is complaining about the deprecated renderlet method. I'm also having trouble with getting the maps to render. Is the library working with dc 2.0.0-beta.19? 

Edit: It seems that the problem is with width being properly set on the div.dc-leaflet.leaflet-container element and its child divs

### PR DESCRIPTION
**Pull request by tayden**
Fix issue with declaring width and heights of div.dc-leaflet where Leaflet map is rendered that caused the map to render improperly. Also updated demo so that it is working again.

Resolves #5

### CODE REVIEW

**Comment by tayden** [comment]
Leaflet maps are added to page multiple time due to this fix, so resubmitting new pull request.

**Comment by gordonwoodhull** [comment]
Yeah, I think only the `px` part was relevant to this fix, although the css formatting is appreciated too.

**Comment by gordonwoodhull** [comment]
Thanks! For future reference, you can continue to push to the same branch to update a pull request.

**Comment by tayden** [comment]
Awesome. Thanks! I'm new to this..

**Pull request closed without merging**
